"""
Database layer for LLM Relay.

Provides SQLAlchemy models and database connection management.
"""

from .connection import (
    check_db_initialized,
    get_db,
    get_db_context,
    get_engine,
    init_db,
    run_migrations,
)
from .document_stores import (
    create_document_store,
    delete_document_store,
    get_all_document_stores,
    get_document_store_by_id,
    get_document_store_by_name,
    get_enabled_document_stores,
    get_stores_with_schedule,
    store_name_available,
    update_document_store,
    update_document_store_index_status,
)
from .live_cache import (
    DEFAULT_TTLS,
    # Data cache
    cache_data_response,
    # Entity cache
    cache_entity,
    cleanup_expired_caches,
    clear_all_caches,
    clear_data_cache,
    clear_entity_cache,
    # Combined
    get_all_cache_stats,
    get_data_cache_stats,
    get_entity_cache_stats,
    get_entity_ttl_days,
    is_cache_enabled,
    lookup_data_cache,
    lookup_entity,
    lookup_entity_with_metadata,
)
from .live_data_sources import (
    create_live_data_source,
    delete_live_data_source,
    get_all_live_data_sources,
    get_enabled_live_data_sources,
    get_live_data_source_by_id,
    get_live_data_source_by_name,
    update_live_data_source,
    update_live_data_source_status,
)
from .live_data_sources import (
    source_name_available as live_source_name_available,
)
from .models import (
    Base,
    CustomModel,
    CustomProvider,
    DailyStats,
    DocumentStore,
    LiveDataCache,
    LiveEntityCache,
    Model,
    ModelOverride,
    OllamaInstance,
    PluginConfig,
    Provider,
    Redirect,
    RequestLog,
    ScheduledPromptExecution,
    Setting,
    SmartAlias,
    smart_alias_stores,
)
from .plugin_configs import (
    create_plugin_config,
    delete_plugin_config,
    get_action_configs,
    get_all_plugin_configs,
    get_document_source_configs,
    get_live_source_configs,
    get_plugin_config,
    get_plugin_config_by_name,
    get_plugin_configs_by_type,
    update_plugin_config,
)
from .redirects import (
    create_redirect,
    delete_redirect,
    find_matching_redirect,
    get_all_redirects,
    get_enabled_redirects,
    get_redirect_by_id,
    get_redirect_by_source,
    increment_redirect_count,
    update_redirect,
)
from .scheduled_prompts import (
    cleanup_old_executions,
    create_execution,
    delete_execution,
    delete_executions_for_alias,
    event_already_scheduled,
    get_execution_by_event,
    get_execution_by_id,
    get_execution_stats,
    get_executions_for_alias,
    get_pending_executions,
    get_recent_executions,
    mark_execution_completed,
    mark_execution_failed,
    mark_execution_running,
    mark_execution_skipped,
    reset_execution_to_pending,
    update_execution_status,
)
from .seed import (
    ensure_seeded,
    seed_models_from_litellm,
    seed_providers,
)
from .settings import (
    delete_setting,
    get_all_settings,
    get_setting,
    set_setting,
)
from .smart_aliases import (
    create_smart_alias,
    delete_smart_alias,
    get_all_smart_aliases,
    get_enabled_smart_aliases,
    get_smart_alias_by_id,
    get_smart_alias_by_name,
    get_smart_tag_by_name,
    reset_smart_alias_stats,
    smart_alias_name_available,
    update_smart_alias,
    update_smart_alias_memory,
    update_smart_alias_stats,
)
from .sync_descriptions import (
    get_available_description_providers,
    get_descriptions_for_models,
    get_model_description,
    sync_model_descriptions,
)

__all__ = [
    # Connection
    "get_db",
    "get_db_context",
    "init_db",
    "run_migrations",
    "check_db_initialized",
    "get_engine",
    # Core models
    "Provider",
    "Model",
    "Setting",
    "Base",
    # Override/custom models
    "ModelOverride",
    "CustomModel",
    "OllamaInstance",
    "CustomProvider",
    # Usage tracking
    "RequestLog",
    "DailyStats",
    # Seeding
    "ensure_seeded",
    "seed_providers",
    "seed_models_from_litellm",
    # Description sync
    "sync_model_descriptions",
    "get_model_description",
    "get_descriptions_for_models",
    "get_available_description_providers",
    # Redirects
    "Redirect",
    "get_all_redirects",
    "get_redirect_by_id",
    "get_redirect_by_source",
    "find_matching_redirect",
    "create_redirect",
    "update_redirect",
    "delete_redirect",
    "increment_redirect_count",
    "get_enabled_redirects",
    # Document Stores
    "DocumentStore",
    "get_all_document_stores",
    "get_document_store_by_name",
    "get_document_store_by_id",
    "create_document_store",
    "update_document_store",
    "update_document_store_index_status",
    "delete_document_store",
    "store_name_available",
    "get_enabled_document_stores",
    "get_stores_with_schedule",
    # Settings
    "get_setting",
    "set_setting",
    "delete_setting",
    "get_all_settings",
    # Smart Aliases (unified routing + enrichment + caching)
    "SmartAlias",
    "smart_alias_stores",
    "get_all_smart_aliases",
    "get_smart_alias_by_name",
    "get_smart_alias_by_id",
    "get_smart_tag_by_name",
    "create_smart_alias",
    "update_smart_alias",
    "update_smart_alias_memory",
    "update_smart_alias_stats",
    "reset_smart_alias_stats",
    "delete_smart_alias",
    "smart_alias_name_available",
    "get_enabled_smart_aliases",
    # Live Data Cache
    "LiveDataCache",
    "LiveEntityCache",
    "cache_data_response",
    "lookup_data_cache",
    "clear_data_cache",
    "get_data_cache_stats",
    "cache_entity",
    "lookup_entity",
    "lookup_entity_with_metadata",
    "clear_entity_cache",
    "get_entity_cache_stats",
    "get_all_cache_stats",
    "clear_all_caches",
    "cleanup_expired_caches",
    "is_cache_enabled",
    "get_entity_ttl_days",
    "DEFAULT_TTLS",
    # Scheduled Prompt Executions
    "ScheduledPromptExecution",
    "get_execution_by_id",
    "get_execution_by_event",
    "get_executions_for_alias",
    "get_pending_executions",
    "get_recent_executions",
    "create_execution",
    "update_execution_status",
    "mark_execution_running",
    "mark_execution_completed",
    "mark_execution_failed",
    "mark_execution_skipped",
    "reset_execution_to_pending",
    "delete_execution",
    "delete_executions_for_alias",
    "cleanup_old_executions",
    "get_execution_stats",
    "event_already_scheduled",
    # Plugin Configs
    "PluginConfig",
    "get_plugin_config",
    "get_plugin_config_by_name",
    "get_plugin_configs_by_type",
    "get_all_plugin_configs",
    "create_plugin_config",
    "update_plugin_config",
    "delete_plugin_config",
    "get_action_configs",
    "get_document_source_configs",
    "get_live_source_configs",
]
